/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import domain.Currency;
import java.awt.Panel;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import logic.Controller;
import logic.Machine;
import logic.Node;
import logic.Node1;
import logic.Node100;
import logic.Node20;
import logic.Node50;

/**
 *
 * @author user
 */
public class FormMain extends javax.swing.JDialog implements DocumentListener {

    private Node chain;

    /**
     * Creates new form FmGlavna
     */
    public FormMain(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setAmount();
        setListener();
        //createChain();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jrb20 = new javax.swing.JRadioButton();
        jrb25 = new javax.swing.JRadioButton();
        jrb30 = new javax.swing.JRadioButton();
        jrb40 = new javax.swing.JRadioButton();
        jrb50 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        txtReturns = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnMake = new javax.swing.JButton();
        btnAddBills = new javax.swing.JButton();
        panelBills1 = new form.components.PanelBills();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Coffe machine");

        buttonGroup1.add(jrb20);
        jrb20.setSelected(true);
        jrb20.setText(" Espreso(20)");
        jrb20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb20ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrb25);
        jrb25.setText(" Espreso with milk (25)");
        jrb25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb25ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrb30);
        jrb30.setText("Cappuccino (30)");
        jrb30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb30ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrb40);
        jrb40.setText("Irish coffe (40)");
        jrb40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb40ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrb50);
        jrb50.setText("Hot chocolate (50)");
        jrb50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb50ActionPerformed(evt);
            }
        });

        jLabel1.setText("Price:");

        txtPrice.setEditable(false);
        txtPrice.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N

        jLabel2.setText("Amount:");

        txtAmount.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N

        txtReturns.setEditable(false);
        txtReturns.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N

        jLabel3.setText("Returns:");

        btnMake.setText("Make coffe");
        btnMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeActionPerformed(evt);
            }
        });

        btnAddBills.setText("Add bills");
        btnAddBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBillsActionPerformed(evt);
            }
        });

        panelBills1.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrb20)
                                    .addComponent(jrb25)
                                    .addComponent(jrb30)
                                    .addComponent(jrb40)
                                    .addComponent(jrb50))
                                .addGap(88, 88, 88))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtAmount)
                                        .addGap(28, 28, 28)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtReturns, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMake, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddBills, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBills1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrb20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReturns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(panelBills1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMake)
                    .addComponent(btnAddBills))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb30ActionPerformed
        // TODO add your handling code here:
        setAmount();
    }//GEN-LAST:event_jrb30ActionPerformed

    private void jrb20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb20ActionPerformed
        // TODO add your handling code here:
        setAmount();
    }//GEN-LAST:event_jrb20ActionPerformed

    private void jrb25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb25ActionPerformed
        // TODO add your handling code here:
        setAmount();
    }//GEN-LAST:event_jrb25ActionPerformed

    private void jrb40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb40ActionPerformed
        // TODO add your handling code here:
        setAmount();
    }//GEN-LAST:event_jrb40ActionPerformed

    private void jrb50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb50ActionPerformed
        // TODO add your handling code here:
        setAmount();
    }//GEN-LAST:event_jrb50ActionPerformed

    private void btnMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeActionPerformed
        try {
            checkEnoughMoney();
            
            //int amountInMachine = Machine.getInstance().calculateAmountIn();
            int amountOfChange = Integer.parseInt(txtReturns.getText());
            int returnAmount = Controller.getInstance().getChain().returnAmount(new Currency(amountOfChange));
            //boolean enoughInMachine = Controller.getInstance().checkEnoughMoney(amountInMachine, amountOfChange);
            
            
            if( returnAmount < amountOfChange){
                int option = JOptionPane.showConfirmDialog(this, "Warning! The machine will not be able to return the whole amount of change.\n" + 
                                                    "Change to return: " + returnAmount + "\n" + 
                                                    "Do you want to buy the product?", "Warning!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if(option == JOptionPane.NO_OPTION){
                    clearAllFields();
                    return;
                }
            }
            
            
            
            Map<String, Integer> map = new HashMap() {
//                {
//                    put("100", 0);
//                    put("50", 0);
//                    put("20", 0);
//                    put("10", 0);
//                    put("1", 0);
//                }
            };
            
            Controller.getInstance().getChain().getCurrency(new Currency(Integer.parseInt(txtReturns.getText().trim())), map);
            
            
            refreshBills(map);
            
            //chain.getCurrency(new Currency(Integer.parseInt(txtReturns.getText().trim())), map);
            
            clearAmountFields();
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error:", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMakeActionPerformed

    private void btnAddBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBillsActionPerformed
//        JFrame billsFrame = new JFrame();
//        billsFrame.add(new PanelBills());
//        billsFrame.pack();
//        billsFrame.setVisible(true);

          JFrame billsFrame = new JFrame();
          billsFrame.add(new FormAddBillsv2());
          billsFrame.pack();
          billsFrame.setVisible(true);
          billsFrame.setLocation(500, 500);

    }//GEN-LAST:event_btnAddBillsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBills;
    private javax.swing.JButton btnMake;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jrb20;
    private javax.swing.JRadioButton jrb25;
    private javax.swing.JRadioButton jrb30;
    private javax.swing.JRadioButton jrb40;
    private javax.swing.JRadioButton jrb50;
    private form.components.PanelBills panelBills1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtReturns;
    // End of variables declaration//GEN-END:variables

    private void setAmount() {
        clearAllFields();

        if (jrb20.isSelected()) {
            txtPrice.setText("20");
        }
        if (jrb25.isSelected()) {
            txtPrice.setText("25");
        }
        if (jrb30.isSelected()) {
            txtPrice.setText("30");
        }
        if (jrb40.isSelected()) {
            txtPrice.setText("40");
        }
        if (jrb50.isSelected()) {
            txtPrice.setText("50");
        }

    }

    private void setListener() {
        txtAmount.getDocument().addDocumentListener(this);
    }

    @Override
    public void insertUpdate(DocumentEvent e) {
        setReturns();
    }

    private void setReturns() throws NumberFormatException {
        try {
            int price = Integer.parseInt(txtPrice.getText());
            int amount = Integer.parseInt(txtAmount.getText());

            int kusur = amount - price;
            txtReturns.setText(kusur + "");
        } catch (Exception e) {
        }
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        setReturns();
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
    }

    private void clearAllFields() {

        txtReturns.setText("");
        txtAmount.setText("");
    }
    
    private void clearAmountFields(){
        txtReturns.setText("");
        txtAmount.setText("");
    }

    private void checkEnoughMoney() throws Exception {
        if (txtAmount.getText().isEmpty()) {
            throw new Exception("Amount is empty");
        }
        int amount = Integer.parseInt(txtAmount.getText().trim());
        int price = Integer.parseInt(txtPrice.getText().trim());
        
        boolean enough = Controller.getInstance().checkEnoughMoney(amount, price);
        if (!enough) {
            throw new Exception("Amount < price");
        }
    }

    private void createChain() {
        Node100 node100 = new Node100();
        Node50 node50 = new Node50();
        Node20 node20 = new Node20();
        Node1 node1 = new Node1();

        node1.setNext(null);
        node20.setNext(node1);
        node50.setNext(node20);
        node100.setNext(node50);

        chain = node100;
    }

    private void refreshBills(Map<String, Integer> map) {
        Controller.getInstance().getChain().refreshPanel(panelBills1, map);
    }
}
